input {
    tcp {
        port => 5000
        codec => json_lines
    }
}

output {
    if [app_name] {
        elasticsearch {
            hosts => ["http://vti-elasticsearch:9200"]
            index => "%{app_name}-logs-%{+YYYY.MM.dd}"
        }
    } else {
        elasticsearch {
            hosts => ["http://vti-elasticsearch:9200"]
            index => "unknown-service-logs-%{+YYYY.MM.dd}"
        }
    }

    stdout { codec => rubydebug }
}