server:
  port: 8282

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1

        - id: promotion-service
          uri: lb://promotion-service
          predicates:
            - Path=/promotions/**
          filters:
            - StripPrefix=1

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventories/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dtn2508
          jwk-set-uri: http://localhost:8080/realms/dtn2508/protocol/openid-connect/certs

logging:
  level:
    root: info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}