spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_order_service?serverTimezone=UTC
    username: root
    password: duc123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        request.timeout.ms: 15000
        linger.ms: 0
      acks: all
    consumer:
      group-id: order-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

server:
  port: 8098

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

data:
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

client:
  product:
    uri: http://product-service/api/v1/products
  promotion:
    uri: http://promotion-service/api/v1/promotions
  inventory:
    uri: http://inventory-service/api/v1/inventories